### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by viovanov** [SUSE/carrier#2]
- [x] replace drone with brigade/argo/prow
- [x] replace nginx with traefik
- [x] add detect script for traefik
- [ ] add detect scripts for each thing, so if they are already setup, don't setup
- [x] add a pipeline to test on GHA with k3s
- [x] drone/brigade should be configured using quarks
- [x] start the shim project
- [ ] apps should have a GUID
- [x] only install QuarksSecret and QuarksJob
- [ ] all resources managed by carrier should be marked, so on uninstall we don't delete anything by accident
- [ ] docs site
- [x] one line installer
- [x] detection for `kind` and `minikube`
- [x] releases with tarballs
- [x] use a docker registry as a component

**Comment by andreas-kupries** [comment]
> detection for kind and minikube

IMHO also for `k3d/k3s`, being Rancher and all that.

**Comment by jimmykarily** [comment]
Most have already been done, some others are deprecated. Closing.
